name: CI
on:
  push:
    branches:
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yml
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.0'
        java-version: '17'
        components: 'native-image'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn test
      env:
        _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
      run: |
        set -e
        ./mvnw -V test